"""Update: new changes to task and history model

Revision ID: 0274a0b11bda
Revises: 
Create Date: 2024-02-27 16:22:34.686397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0274a0b11bda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('added_minutes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_histories_added_minutes'), 'histories', ['added_minutes'], unique=False)
    op.add_column('tasks', sa.Column('repeat', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('repeated_date', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('repeated_days', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_repeat'), 'tasks', ['repeat'], unique=False)
    op.create_index(op.f('ix_tasks_repeated_date'), 'tasks', ['repeated_date'], unique=False)
    op.create_index(op.f('ix_tasks_repeated_days'), 'tasks', ['repeated_days'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_repeated_days'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_repeated_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_repeat'), table_name='tasks')
    op.drop_column('tasks', 'repeated_days')
    op.drop_column('tasks', 'repeated_date')
    op.drop_column('tasks', 'repeat')
    op.drop_index(op.f('ix_histories_added_minutes'), table_name='histories')
    op.drop_column('histories', 'added_minutes')
    # ### end Alembic commands ###
