"""Create: new model history

Revision ID: 2f0a9ce76876
Revises: 
Create Date: 2024-01-31 10:32:56.615121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0a9ce76876'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_created_at'), 'histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_histories_deleted_at'), 'histories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_histories_description'), 'histories', ['description'], unique=False)
    op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
    op.create_index(op.f('ix_histories_status'), 'histories', ['status'], unique=False)
    op.create_index(op.f('ix_histories_title'), 'histories', ['title'], unique=False)
    op.create_index(op.f('ix_histories_updated_at'), 'histories', ['updated_at'], unique=False)
    op.drop_index('ix_history_created_at', table_name='history')
    op.drop_index('ix_history_deleted_at', table_name='history')
    op.drop_index('ix_history_description', table_name='history')
    op.drop_index('ix_history_id', table_name='history')
    op.drop_index('ix_history_status', table_name='history')
    op.drop_index('ix_history_title', table_name='history')
    op.drop_index('ix_history_updated_at', table_name='history')
    op.drop_table('history')
    op.drop_constraint('tasks_history_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'histories', ['history_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_history_id_fkey', 'tasks', 'history', ['history_id'], ['id'])
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='history_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='history_pkey')
    )
    op.create_index('ix_history_updated_at', 'history', ['updated_at'], unique=False)
    op.create_index('ix_history_title', 'history', ['title'], unique=False)
    op.create_index('ix_history_status', 'history', ['status'], unique=False)
    op.create_index('ix_history_id', 'history', ['id'], unique=False)
    op.create_index('ix_history_description', 'history', ['description'], unique=False)
    op.create_index('ix_history_deleted_at', 'history', ['deleted_at'], unique=False)
    op.create_index('ix_history_created_at', 'history', ['created_at'], unique=False)
    op.drop_index(op.f('ix_histories_updated_at'), table_name='histories')
    op.drop_index(op.f('ix_histories_title'), table_name='histories')
    op.drop_index(op.f('ix_histories_status'), table_name='histories')
    op.drop_index(op.f('ix_histories_id'), table_name='histories')
    op.drop_index(op.f('ix_histories_description'), table_name='histories')
    op.drop_index(op.f('ix_histories_deleted_at'), table_name='histories')
    op.drop_index(op.f('ix_histories_created_at'), table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
