"""Update: model task v3

Revision ID: 5da43b76657d
Revises: 
Create Date: 2024-01-26 14:03:39.309877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da43b76657d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_index('ix_alerts_created_at', table_name='alerts')
    op.drop_index('ix_alerts_deleted_at', table_name='alerts')
    op.drop_index('ix_alerts_description', table_name='alerts')
    op.drop_index('ix_alerts_hour', table_name='alerts')
    op.drop_index('ix_alerts_id', table_name='alerts')
    op.drop_index('ix_alerts_minute', table_name='alerts')
    op.drop_index('ix_alerts_name', table_name='alerts')
    op.drop_index('ix_alerts_period', table_name='alerts')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_updated_at', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_categories_created_at', table_name='categories')
    op.drop_index('ix_categories_deleted_at', table_name='categories')
    op.drop_index('ix_categories_description', table_name='categories')
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_index('ix_categories_status', table_name='categories')
    op.drop_index('ix_categories_updated_at', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_type_alerts_created_at', table_name='type_alerts')
    op.drop_index('ix_type_alerts_deleted_at', table_name='type_alerts')
    op.drop_index('ix_type_alerts_description', table_name='type_alerts')
    op.drop_index('ix_type_alerts_id', table_name='type_alerts')
    op.drop_index('ix_type_alerts_name', table_name='type_alerts')
    op.drop_index('ix_type_alerts_status', table_name='type_alerts')
    op.drop_index('ix_type_alerts_updated_at', table_name='type_alerts')
    op.drop_table('type_alerts')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_users_deleted_at', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_first_name', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_last_name', table_name='users')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_updated_at', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_updated_at', 'users', ['updated_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_table('type_alerts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('type_alerts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='type_alerts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_type_alerts_updated_at', 'type_alerts', ['updated_at'], unique=False)
    op.create_index('ix_type_alerts_status', 'type_alerts', ['status'], unique=False)
    op.create_index('ix_type_alerts_name', 'type_alerts', ['name'], unique=False)
    op.create_index('ix_type_alerts_id', 'type_alerts', ['id'], unique=False)
    op.create_index('ix_type_alerts_description', 'type_alerts', ['description'], unique=False)
    op.create_index('ix_type_alerts_deleted_at', 'type_alerts', ['deleted_at'], unique=False)
    op.create_index('ix_type_alerts_created_at', 'type_alerts', ['created_at'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('categories_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_categories_updated_at', 'categories', ['updated_at'], unique=False)
    op.create_index('ix_categories_status', 'categories', ['status'], unique=False)
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    op.create_index('ix_categories_description', 'categories', ['description'], unique=False)
    op.create_index('ix_categories_deleted_at', 'categories', ['deleted_at'], unique=False)
    op.create_index('ix_categories_created_at', 'categories', ['created_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_alert_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_alert_id'], ['type_alerts.id'], name='alerts_type_alert_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alerts_pkey')
    )
    op.create_index('ix_alerts_updated_at', 'alerts', ['updated_at'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_period', 'alerts', ['period'], unique=False)
    op.create_index('ix_alerts_name', 'alerts', ['name'], unique=False)
    op.create_index('ix_alerts_minute', 'alerts', ['minute'], unique=False)
    op.create_index('ix_alerts_id', 'alerts', ['id'], unique=False)
    op.create_index('ix_alerts_hour', 'alerts', ['hour'], unique=False)
    op.create_index('ix_alerts_description', 'alerts', ['description'], unique=False)
    op.create_index('ix_alerts_deleted_at', 'alerts', ['deleted_at'], unique=False)
    op.create_index('ix_alerts_created_at', 'alerts', ['created_at'], unique=False)
    op.create_table('association',
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='association_category_id_fkey')
    )
    # ### end Alembic commands ###
