"""Add column to task

Revision ID: c88126c31f12
Revises: d2ca4fd16cef
Create Date: 2024-03-01 14:22:19.922596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88126c31f12'
down_revision: Union[str, None] = 'd2ca4fd16cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('minutes_total', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_minutes_total'), 'tasks', ['minutes_total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_minutes_total'), table_name='tasks')
    op.drop_column('tasks', 'minutes_total')
    # ### end Alembic commands ###
