name: Task List CI/CD

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Create env File
        run: |
          echo "POSTGRES_USER={{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD={{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB={{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_HOST={{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT={{ secrets.POSTGRES_PORT }}" >> .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Run tests
        run: |
          coverage run -m pytest 
          coverage report -m 
          coverage xml


  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}



